### ISSUE TITLE
Parts of the code that could be improved in version 2.1.5

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-core#234]
Parts of the code that could be improved: ● No env variables ● Transactions file naming. It should be in lowercase or camelcase, not snake case

**Comment by ManuGowda** [comment]
● No env variables: Please provide further information regarding this.
● Transactions file naming: Git can not identify the camelCase changes to file names and it can have side effects while building the changes, here are some references https://github.com/spf13/jWalterWeatherman/issues/22
Explanation: Git by default set ignorecase to `true`, in order to allow the camelCase file names we need to override the config `git config core.ignorecase false` which is not a good practice in general.

**Comment by karmacoma** [comment]
Skipping no env variables until we get further information.
