### ISSUE TITLE
Deleting data-directory is not detected or reported

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-core#420]
### Expected behavior
There should be some warning/error message or the node should stop/crash when the data-directory is deleted accidentally or intentionally. Otherwise, the forger has no way of recovering the lost "forgerInfo" data he may need to continue/restart forging

### Actual behavior
The node continues to operate without any indication

### Steps to reproduce
Run a node. Delete the data-directory usually present at `~/.lisk`

### Which version(s) does this affect? (Environment, OS, etc...)
3.*

**Comment by nazarhussain** [comment]
https://github.com/Level/rocksdb/issues/165

**Comment by nazarhussain** [comment]
## Problem
As per my findings RocksDB has premature support for respond to issues related to Disk I/O. The issues related to Disk I/O can be these but not limited to:
- The data directory is no more available (our case)
- The data directory is not accessible (may be someone changed permission)
- The disk latency increased and writing to disk not performed
- The disk is full and you can’t write any more

For any such Disk I/O issues, RocksDB shadow the problem and keep performing in-memory.

## Research
In all such scenarios the behaviour of RocksDB is not well defined. Their repo contains many open issues related to Disk I/O. The maintainer of the RocksDB nodejs binding [described it as](https://github.com/Level/rocksdb/issues/165#issuecomment-754892635):

> Behaviour towards external changes to Disk is undefined. RocksDB can crash, it can throw error or it could do nothing.

What I observed though is a defined but very strange behaviour. For any failure towards Disk I/O, RocksDB stopped writing to disk and start behaving is in-memory store silently.

There is a configuration in Rocks db called `paranoid_checks` The code comment describe it as:

> If true, RocksDB will aggressively check consistency of the data. Also, if any of the writes to the database fails (Put, Delete, Merge, Write), the database will switch to read-only mode and fail all other Write operations.

I don’t know what else could mean by consistency of the data here, if its not persisted. The default value for this configuration is true, but still its not behaving strange. Probably they have very different meaning of data consistency.
In contrary I run similar tests on LevelDB and found that Level DB fail on every write operations as soon any kind of Disk I/O issue occurred.

## Findings  

While I was debugging the issue I found out that the underlying issue is opted due to nature of `*NIX` systems.  If we use linux commands `rm` or similar or use any nodejs function `unlink` or `unlinkSync`, all those relies on `*NIX` syscall `unlink`. And behaviour of the `unlink` is that it removes the file name entry but don't delete the file if any process is accessing it. As soon all processes which are accessing the file are closed, the file is deleted from disk. Some nice details are mentioned [here](https://stackoverflow.com/a/22252641). 

To be more detailed informaiton 

> An open file is deleted only when all file descriptors are closed
>
>In addition to maintaining a link count for each i-node, the kernel also counts open
file descriptions for the file (see Figure 5-2, on page 95). If the last link to a file is
removed and any processes hold open descriptors referring to the file, the file
won’t actually be deleted until all of the descriptors are closed.
>
> The Linux Programming Interface by Michael KerrisK on Page 346

To confirm this, we can run similar test on the log file. Just `tail -f ~/.lisk-core/logs/lisk.log`. You will start seeing log entries. And now just go into other terminal  and run `rm -r ~/.lisk-core`. You will notice that directory and all files including logs are deleted but in other terminal the `tail` will still be working and showing the logs. 


## Solution 1
There is one solution to this problem within RocksDB. It is called flushing the data. The flushing make sure all data in-memory is written to disk with the particular db name. And while flushing if there is any Disk I/O issue it failed the operation. If we flush after every block write, we can make sure our data is persisted. The problem with this solution is RocksDB binding that we are using does not support Flush  interface. So we have to probably fork and add this interface support and then share it with them.

## Solution 2
Not checked into details but switching to LevelDB may not introduce breaking change and we cover this problem. The side effects should also be calculated. In LevelDB for such scenarios every write call fails if database files are removed. 


## Conclusion 

As we observed this is inherit behaviour from the `*NIX` systems and the way RocksDB handles the file connections, not some issue within our framework. Such scenarios are very rare in nature and our application makes copy of same data to other nodes, so in case user encounter a problem can easily sync up from other nodes. 

With that said we decided to not look into fixing this issue right now. We encourage node operators to have some external tools to monitor their file system to avoid any such issues.
