### ISSUE TITLE
Installing lisk-core 3.0.0-beta.5 via npm on Macbook w/ M1 chip not successful

### ISSUE THREAD

**Issue by Hupka** [LiskHQ/lisk-core#479]
### Expected behavior

Executing command `npm install --global --production lisk-core` on MacOS (with Node 12) installs the lisk-core software on Macbook with M1 chip.

### Actual behavior

The installation procedure fails; 

```bash
rocksdb@4.1.0 install /opt/homebrew/lib/node_modules/lisk-core/node_modules/rocksdb
> node-gyp-build

  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/db/auto_roll_logger.o
clang: error: the clang compiler does not support '-march=native'
```

### Steps to reproduce

* Have Macbook with Apple's new M1 chip
* Following installation instructions at https://lisk.io/documentation/lisk-core/v3/setup/npm.html
* Include non-documented step `brew install autoconf automake libtool` which is included in [`beta1` instructions](https://lisk.io/documentation/lisk-core/v3-beta.1/setup/source.html) `lisk-core`

### Which version(s) does this affect? (Environment, OS, etc...)

`lisk-core 3.0.0-beta.5`, potentially earlier versions as well due to the nature of the error. 

### Potential root cause

The error message indicates a compilation error. This might be caused by the new chipset, as this [stackoverflow thread](https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1) indicated.

**Comment by ManuGowda** [comment]
Refer: https://github.com/Level/rocksdb/issues/169

**Comment by Lemii** [comment]
https://dev.lisk.com/t/installing-the-lisk-sdk-on-m1-macs/

**Comment by Nazgolze** [comment]
> https://dev.lisk.com/t/installing-the-lisk-sdk-on-m1-macs/

Hmmm. I wonder if that's the x86_64 version and it's running under emulation :thinking:

I did manage to get a build working on the M1, I will post the full details here shortly.......

**Comment by Nazgolze** [comment]
So when you go down the rabbit hole, you run into a couple issues.
There's the node.js rocksdb binding issue that @ManuGowda linked too. I worked around it by forking and removing the `march=native` line. It also tries to test against electron, but there is no electron build for Mac ARM, so this fails. I deleted all references to electron in the fork (fork of an older version of the binding to match what we're using, in newer versions, I don't think electron is an issue)

You eventually run into https://github.com/chrisa/node-dtrace-provider/issues/118.
This is an optional dependency of bunyan, but it always gets pulled in.
So the `dtrace-provider` directory needs to get deleted from `node_modules` after `npm install` or `yarn` (you can try to install with no optional dependencies, but sodium-native probably wouldn't get pulled in then either).

to bring it all together, I ended up using verdaccio and publishing locally. No amount of `yarn link` and `npm link` for the rocksdb binding worked at the lisk-core step.

I can't recommend this to everybody :sweat_smile:, but I think we can use this info so that future releases do build smoothly. Stay tuned.....

**Comment by ManuGowda** [comment]
@Nazgolze your fix is released with [v5.1.0](https://github.com/Level/rocksdb/releases/tag/v5.1.0), maybe try to test with 5.1.0 and see if it works on M1? then we can include it in our next release to support M1. 

Also found that it had some issue with macOS [11.5.1](https://github.com/Level/rocksdb/issues/177), but updating to latest version for RocksDB seem to solve the problem.

**Comment by ManuGowda** [comment]
@Hupka as a workaround you can try `arch -x86_64 bash` and verify `node -p process.arch` to make sure its `x64`.

Then try `npm install --global --production lisk-core`, you will be able install `lisk-core@3.0.3`.

Please let us know if the workaround helped your.

**Comment by EvanXzj** [comment]
MacBook Air (M1, 2020)
Node Version: v16.14.0
lisk-sdk: 5.2.1

**found same error:**

```
npm install lisk-sdk@5.2.1


......
> rocksdb@4.1.0 install /private/tmp/lsk-demo/node_modules/rocksdb
> node-gyp-build

(node:58956) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/db/auto_roll_logger.o
clang: error: the clang compiler does not support '-march=native'
......
```

@ManuGowda  Please help.

**Comment by EvanXzj** [comment]
@przemerr  
rocksdb@4.1.0 was @liskhq/lisk-db's dependency, how can i update it to 5.2.0?

**Comment by przemerr** [comment]
i guess it should be updated by HQ, you can try this workaround https://dev.lisk.com/t/installing-the-lisk-sdk-on-m1-macs/462 by installing node.js differently

**Comment by ManuGowda** [comment]
@EvanXzj please follow the recommendation from @przemerr.

**Comment by EvanXzj** [comment]
@ManuGowda @przemerr  I have tried it, and I can install the lisk-sdk@5.2.0 package on M1 Mac with Node v12.21.0, but it still doesn't solve my problem😅.

I am writting a desktop application using Electron 12 and lisk-sdk on a M1 computer. Electron only supports M1 computers after v11+, and the minimum Node version of Electron 12 required is v14+, it's embarrassing. So can you guys help solve this problem and reissue a verson lisk-sdk pkg

**Comment by przemerr** [comment]
the SDK v5 is only compatible with node.js v12, regardless of M1 chip or OS. SDK v6 will be compatible with a higher version of node.js. So for now you probably need to run it in a VM environment with a lower electron version.

**Comment by sameersubudhi** [comment]
Closing the issue. Following the instructions mentioned [here](https://lisk.com/documentation/lisk-core/setup/npm.html), I was able to install the lisk-core CLI on a new M1 MacBook.
