### ISSUE TITLE
Environment variable are not honored when `lisk-core` is started from Docker

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-core#831]
### Expected behavior
The following command should start just fine:
```bash
docker run -it --rm -e LISK_NETWORK=betanet --volume lisk-data:/home/lisk/.lisk lisk/core:4.0.0-beta.5
```

### Actual behavior

Sadly the `LISK_NETWORK` env variable is not honored and therefore the app cannot start.

### Which version(s) does this affect? (Environment, OS, etc...)

`lisk/core:4.0.0-beta.5`

**Comment by sameersubudhi** [comment]
@JesusTheHun The docker image works as expected. Please try as following (`start` at the end):

```
docker run -it --rm -e LISK_NETWORK=betanet --volume lisk-data:/home/lisk/.lisk lisk/core:4.0.0-beta.5 start
```

You'll have to specify the lisk-core command you'd like to execute since the ENTRYPOINT is defined as `/home/lisk/bin/run`, which is equivalent of just executing the CLI `lisk-core` after you install it from NPM. Please refer the [Docker README](https://github.com/LiskHQ/lisk-core/tree/release/4.0.0/docker) and let me know if you have got any further queries.

In case there are no more doubts, please feel free to close the issue 🙏

**Comment by sameersubudhi** [comment]
Closing the issue, since there's nothing to be addressed here.
