### ISSUE TITLE
Update to only use lisk-sdk

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-core#93]
### Expected behavior
lisk-core should be able to be built only using lisk-sdk.

### Actual behavior
It uses multiple packages.
`@liskhq/lisk-cryptography`
`@liskhq/lisk-transactions`
etc

### Which version(s) does this affect? (Environment, OS, etc...)
2.0-

**Comment by michielmulders** [comment]
Was able to remove `lisk-cryptography` easily, however, having struggels with `lisk-transactions` due to the following problem: https://github.com/Microsoft/TypeScript/issues/23110

**Comment by michielmulders** [comment]
To expand further on this:
For `lisk-cryptography` it is possible to remove the dependency and use `lisk-sdk` destructuring.
However, for `lisk-transactions` I get issues with destructuring or even normal import of the required objects from `lisk-sdk`.

The issue is related to the d.ts declarations file Typescript generates: `Exported variable has or is using private name`. An example of the issue is created [here]( https://github.com/Microsoft/TypeScript/issues/6307#issuecomment-360182089)

Minimal reproduction:
```
# a.ts

interface A {
  m: string;
}

export function f(a: A): string {
  return a.m;
}
```

$ tsc -d a.ts
a.ts(5,22): error TS4078: Parameter 'a' of exported function has or
is using private name 'A'.


Expected:

```
# a.d.ts

interface A {
    m: string;
}

export function f(a: A): string {
  return a.m;
}
```

**Comment by michielmulders** [comment]
A user of a should be able to call `f({m: "hello"})` (and typecheck against the unexported declaration), but not necessarily refer to the interface A directly by name.

Note that unexported types do get written to declaration files. E.g. if a.ts has only `interface A {}`, `a.d.ts` gets the unexported declaration `interface A {}`.

**Comment by michielmulders** [comment]
If you compare the exported interface of tx and crypto.
crypto: node_modules/@liskhq/lisk-transactions/dist-node/index.d.ts
```
import * as constants from './constants';
export * from './buffer';
export * from './convert';
export * from './encrypt';
export * from './hash';
export * from './keys';
export * from './sign';
export { constants };
```
--> All public interfaces are exported.

tx:
```
import * as BigNum from '@liskhq/bignum';
import { transfer } from './0_transfer';
import { TransferTransaction } from './0_transfer_transaction';
import { registerSecondPassphrase } from './1_register_second_passphrase';
import { SecondSignatureTransaction } from './1_second_signature_transaction';
import { DelegateTransaction } from './2_delegate_transaction';
import { registerDelegate } from './2_register_delegate';
import { castVotes } from './3_cast_votes';
import { VoteTransaction } from './3_vote_transaction';
import { MultisignatureTransaction } from './4_multisignature_transaction';
import { registerMultisignature } from './4_register_multisignature_account';
import { createDapp } from './5_create_dapp';
```
--> Only few public interfaces are exported.
The issue happens because we use types that are not exported as input for certain functions that are exposed.

**Comment by michielmulders** [comment]
@shuse2 comment:
It’s because SDK is in javascript.
It’s not creating this link to the `lisk-transactions`.
If we use directly from SDK, it doesn’t know about the `lisk-transactions` in Typescript way.
